import { useContext } from 'react'
import Head from 'next/head'
import { UserContext } from '../context/SpotifyUserContext'
import HomeView from '../components/Home/HomeView'

export default function Home() {
  const { user } = useContext(UserContext)

  return (
    <div >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HomeView />
    </div>
  )
}
