import { useContext } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import { scopes } from '../utilities'
import { UserContext } from '../context/SpotifyUserContext'
import { authEndpoint, redirectUri } from './api/endpoints'

const inter = Inter({ subsets: ['latin'] })

const clientId = process.env.NEXT_PUBLIC_SPOTIFY_CLIENT_ID

export default function Home() {
  const loginUrl = `${authEndpoint}?client_id=${clientId}&redirect_uri=${redirectUri}&scope=${scopes.join("%20")}&response_type=token&show_dialogue=true`
  const { user, getTopArtists } = useContext(UserContext)

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex flex-col justify-center items-center">
        Hello Spotify world
        {user && (
          <>
            <p>{user.country}</p>
            <p>{user.display_name}</p>
            {user?.images && (
              <Image width={10} height={10} src={"https://i.scdn.co/image/ab6775700000ee855b2a089e5eaf309a133f8cd6"} alt="profile pic" />
            )}
          </>
        )}
        <button
          className="w-1/12 bg-slate-700 text-green-600 rounded-full p-3 font-bold hover:text-slate-700 hover:bg-slate-200"
          onClick={getTopArtists}
        >
          Get Top Artists
        </button>
        <a
          href={loginUrl}
          className="w-1/12 bg-slate-700 text-green-600 rounded-full p-3 font-bold hover:text-slate-700 hover:bg-slate-200"
        >
          Login real
        </a>
        <Link href="/artist">Go to artist page</Link>
      </div>
    </>
  )
}
